### PR TITLE
Change homework status

### PR DESCRIPTION
**Pull request by arieivs**
incomplete! but nothing is broken I think

### CODE REVIEW

**Comment by arieivs** [comment]
Merge only if you intend to use this code

**Comment by arieivs** [comment]
Ok, I'm going to continue working in this branch now, do not merge it until further commits

**Comment by on-laf** [comment]
Ok

**Comment by arieivs** [comment]
OUR STUDENTS FLASHCARDS ARE WORKING FULLY 🥳

**Pull request merged**
