### PR TITLE
changes the font color on both sign in pages, fixed the vh to 60 so t…

### PR DESCRIPTION
**Pull request by vitorest**
…hat maybe in the future we can apply an image (checkout Dribble sign up page - they use a vertical img on the left side ..hmm sending screenshots so that you can check and merge

### CODE REVIEW

**Comment by vitorest** [comment]
image

**Comment by vitorest** [comment]
image

**Comment by vitorest** [comment]
sending you one image that i think would look amazing in this page  --> slack #persed

**Comment by arieivs** [comment]
Vitor, the border of the Sign up button is still blue 🙃 could you put it pink as well?

**Comment by vitorest** [comment]
Sure, i will

**Pull request merged**
